/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace QuestLockCore {
      
    export type QuestStruct = {id: BigNumberish, creator: AddressLike, rewardToken: AddressLike, rewardAmount: BigNumberish, badgeId: BigNumberish, startTime: BigNumberish, deadline: BigNumberish, maxClaims: BigNumberish, totalClaims: BigNumberish, minScore: BigNumberish, active: boolean}

    export type QuestStructOutput = [id: bigint, creator: string, rewardToken: string, rewardAmount: bigint, badgeId: bigint, startTime: bigint, deadline: bigint, maxClaims: bigint, totalClaims: bigint, minScore: bigint, active: boolean] & {id: bigint, creator: string, rewardToken: string, rewardAmount: bigint, badgeId: bigint, startTime: bigint, deadline: bigint, maxClaims: bigint, totalClaims: bigint, minScore: bigint, active: boolean }
  

    export type SubmissionStruct = {proofHash: BytesLike, attestationUID: BytesLike, score: BigNumberish, status: BigNumberish, submittedAt: BigNumberish, reviewedAt: BigNumberish, claimedAt: BigNumberish}

    export type SubmissionStructOutput = [proofHash: string, attestationUID: string, score: bigint, status: bigint, submittedAt: bigint, reviewedAt: bigint, claimedAt: bigint] & {proofHash: string, attestationUID: string, score: bigint, status: bigint, submittedAt: bigint, reviewedAt: bigint, claimedAt: bigint }
  
    }

  export interface QuestLockCoreInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "PAUSER_ROLE" | "QUEST_CREATOR_ROLE" | "VERIFIER_ROLE" | "approveSubmission" | "badgeContract" | "claimReward" | "claimRewardFor" | "createQuest" | "getQuest" | "getRewardBalance" | "getRoleAdmin" | "getSubmission" | "grantRole" | "hasRole" | "pause" | "pauseQuest" | "paused" | "questCount" | "quests" | "rejectSubmission" | "renounceRole" | "revokeRole" | "submissions" | "submitAndApprove" | "submitProofHash" | "submitProofHashFor" | "supportsInterface" | "unpause" | "unpauseQuest"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Paused" | "ProofSubmitted" | "QuestCreated" | "QuestPaused" | "QuestUpdated" | "RewardClaimed" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "SubmissionApproved" | "SubmissionRejected" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'QUEST_CREATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'VERIFIER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveSubmission', values: [BigNumberish, AddressLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'badgeContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimReward', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimRewardFor', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createQuest', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getQuest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRewardBalance', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSubmission', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseQuest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'questCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'quests', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectSubmission', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'submissions', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'submitAndApprove', values: [BigNumberish, AddressLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitProofHash', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'submitProofHashFor', values: [BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpauseQuest', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'QUEST_CREATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VERIFIER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveSubmission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'badgeContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRewardFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createQuest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getQuest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRewardBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSubmission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseQuest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'questCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectSubmission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submissions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitAndApprove', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitProofHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitProofHashFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseQuest', data: BytesLike): Result;
  }

  
    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProofSubmittedEvent {
      export type InputTuple = [questId: BigNumberish, user: AddressLike, proofHash: BytesLike];
      export type OutputTuple = [questId: bigint, user: string, proofHash: string];
      export interface OutputObject {questId: bigint, user: string, proofHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QuestCreatedEvent {
      export type InputTuple = [questId: BigNumberish, creator: AddressLike, rewardToken: AddressLike, rewardAmount: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [questId: bigint, creator: string, rewardToken: string, rewardAmount: bigint, deadline: bigint];
      export interface OutputObject {questId: bigint, creator: string, rewardToken: string, rewardAmount: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QuestPausedEvent {
      export type InputTuple = [questId: BigNumberish];
      export type OutputTuple = [questId: bigint];
      export interface OutputObject {questId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QuestUpdatedEvent {
      export type InputTuple = [questId: BigNumberish];
      export type OutputTuple = [questId: bigint];
      export interface OutputObject {questId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardClaimedEvent {
      export type InputTuple = [questId: BigNumberish, user: AddressLike, rewardAmount: BigNumberish, badgeId: BigNumberish];
      export type OutputTuple = [questId: bigint, user: string, rewardAmount: bigint, badgeId: bigint];
      export interface OutputObject {questId: bigint, user: string, rewardAmount: bigint, badgeId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SubmissionApprovedEvent {
      export type InputTuple = [questId: BigNumberish, user: AddressLike, attestationUID: BytesLike, score: BigNumberish];
      export type OutputTuple = [questId: bigint, user: string, attestationUID: string, score: bigint];
      export interface OutputObject {questId: bigint, user: string, attestationUID: string, score: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SubmissionRejectedEvent {
      export type InputTuple = [questId: BigNumberish, user: AddressLike];
      export type OutputTuple = [questId: bigint, user: string];
      export interface OutputObject {questId: bigint, user: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface QuestLockCore extends BaseContract {
    
    connect(runner?: ContractRunner | null): QuestLockCore;
    waitForDeployment(): Promise<this>;

    interface: QuestLockCoreInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    QUEST_CREATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    VERIFIER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approveSubmission: TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, proofHash: BytesLike, attestationUID: BytesLike, score: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    badgeContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    claimReward: TypedContractMethod<
      [questId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimRewardFor: TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    createQuest: TypedContractMethod<
      [rewardToken: AddressLike, rewardAmount: BigNumberish, badgeId: BigNumberish, startTime: BigNumberish, deadline: BigNumberish, maxClaims: BigNumberish, minScore: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getQuest: TypedContractMethod<
      [questId: BigNumberish, ],
      [QuestLockCore.QuestStructOutput],
      'view'
    >
    

    
    getRewardBalance: TypedContractMethod<
      [questId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSubmission: TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, ],
      [QuestLockCore.SubmissionStructOutput],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    pauseQuest: TypedContractMethod<
      [questId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    questCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    quests: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, creator: string, rewardToken: string, rewardAmount: bigint, badgeId: bigint, startTime: bigint, deadline: bigint, maxClaims: bigint, totalClaims: bigint, minScore: bigint, active: boolean }],
      'view'
    >
    

    
    rejectSubmission: TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    submissions: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint] & {proofHash: string, attestationUID: string, score: bigint, status: bigint, submittedAt: bigint, reviewedAt: bigint, claimedAt: bigint }],
      'view'
    >
    

    
    submitAndApprove: TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, proofHash: BytesLike, attestationUID: BytesLike, score: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitProofHash: TypedContractMethod<
      [questId: BigNumberish, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitProofHashFor: TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    unpauseQuest: TypedContractMethod<
      [questId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'QUEST_CREATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'VERIFIER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approveSubmission'): TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, proofHash: BytesLike, attestationUID: BytesLike, score: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'badgeContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'claimReward'): TypedContractMethod<
      [questId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimRewardFor'): TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createQuest'): TypedContractMethod<
      [rewardToken: AddressLike, rewardAmount: BigNumberish, badgeId: BigNumberish, startTime: BigNumberish, deadline: BigNumberish, maxClaims: BigNumberish, minScore: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getQuest'): TypedContractMethod<
      [questId: BigNumberish, ],
      [QuestLockCore.QuestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRewardBalance'): TypedContractMethod<
      [questId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSubmission'): TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, ],
      [QuestLockCore.SubmissionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pauseQuest'): TypedContractMethod<
      [questId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'questCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quests'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, creator: string, rewardToken: string, rewardAmount: bigint, badgeId: bigint, startTime: bigint, deadline: bigint, maxClaims: bigint, totalClaims: bigint, minScore: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'rejectSubmission'): TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submissions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint] & {proofHash: string, attestationUID: string, score: bigint, status: bigint, submittedAt: bigint, reviewedAt: bigint, claimedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'submitAndApprove'): TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, proofHash: BytesLike, attestationUID: BytesLike, score: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitProofHash'): TypedContractMethod<
      [questId: BigNumberish, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitProofHashFor'): TypedContractMethod<
      [questId: BigNumberish, user: AddressLike, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpauseQuest'): TypedContractMethod<
      [questId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'ProofSubmitted'): TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
getEvent(key: 'QuestCreated'): TypedContractEvent<QuestCreatedEvent.InputTuple, QuestCreatedEvent.OutputTuple, QuestCreatedEvent.OutputObject>;
getEvent(key: 'QuestPaused'): TypedContractEvent<QuestPausedEvent.InputTuple, QuestPausedEvent.OutputTuple, QuestPausedEvent.OutputObject>;
getEvent(key: 'QuestUpdated'): TypedContractEvent<QuestUpdatedEvent.InputTuple, QuestUpdatedEvent.OutputTuple, QuestUpdatedEvent.OutputObject>;
getEvent(key: 'RewardClaimed'): TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'SubmissionApproved'): TypedContractEvent<SubmissionApprovedEvent.InputTuple, SubmissionApprovedEvent.OutputTuple, SubmissionApprovedEvent.OutputObject>;
getEvent(key: 'SubmissionRejected'): TypedContractEvent<SubmissionRejectedEvent.InputTuple, SubmissionRejectedEvent.OutputTuple, SubmissionRejectedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'ProofSubmitted(uint256,address,bytes32)': TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
      ProofSubmitted: TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
    

      'QuestCreated(uint256,address,address,uint256,uint256)': TypedContractEvent<QuestCreatedEvent.InputTuple, QuestCreatedEvent.OutputTuple, QuestCreatedEvent.OutputObject>;
      QuestCreated: TypedContractEvent<QuestCreatedEvent.InputTuple, QuestCreatedEvent.OutputTuple, QuestCreatedEvent.OutputObject>;
    

      'QuestPaused(uint256)': TypedContractEvent<QuestPausedEvent.InputTuple, QuestPausedEvent.OutputTuple, QuestPausedEvent.OutputObject>;
      QuestPaused: TypedContractEvent<QuestPausedEvent.InputTuple, QuestPausedEvent.OutputTuple, QuestPausedEvent.OutputObject>;
    

      'QuestUpdated(uint256)': TypedContractEvent<QuestUpdatedEvent.InputTuple, QuestUpdatedEvent.OutputTuple, QuestUpdatedEvent.OutputObject>;
      QuestUpdated: TypedContractEvent<QuestUpdatedEvent.InputTuple, QuestUpdatedEvent.OutputTuple, QuestUpdatedEvent.OutputObject>;
    

      'RewardClaimed(uint256,address,uint256,uint256)': TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
      RewardClaimed: TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'SubmissionApproved(uint256,address,bytes32,uint16)': TypedContractEvent<SubmissionApprovedEvent.InputTuple, SubmissionApprovedEvent.OutputTuple, SubmissionApprovedEvent.OutputObject>;
      SubmissionApproved: TypedContractEvent<SubmissionApprovedEvent.InputTuple, SubmissionApprovedEvent.OutputTuple, SubmissionApprovedEvent.OutputObject>;
    

      'SubmissionRejected(uint256,address)': TypedContractEvent<SubmissionRejectedEvent.InputTuple, SubmissionRejectedEvent.OutputTuple, SubmissionRejectedEvent.OutputObject>;
      SubmissionRejected: TypedContractEvent<SubmissionRejectedEvent.InputTuple, SubmissionRejectedEvent.OutputTuple, SubmissionRejectedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }